site_name: Interview

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - mdx_truly_sane_lists
